/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M20
 * Generated at: 2019-03-31 12:13:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.products;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("<meta http-equiv=\"Content-Language\" content=\"zh-cn\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<LINK href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/css/Style.css\"\r\n");
      out.write("\ttype=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</HEAD>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<form id=\"userAction_save_do\" name=\"Form1\"\r\n");
      out.write("\t\taction=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/addproduct\" method=\"post\">\r\n");
      out.write("\t\t&nbsp;\r\n");
      out.write("\t\t<table cellSpacing=\"1\" cellPadding=\"5\" width=\"100%\" align=\"center\"\r\n");
      out.write("\t\t\tbgColor=\"#eeeeee\" style=\"border: 1px solid #8ba7e3\" border=\"0\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"ta_01\" align=\"center\" bgColor=\"#afd1f3\" colSpan=\"4\"\r\n");
      out.write("\t\t\t\t\theight=\"26\"><strong><STRONG>添加商品</STRONG> </strong>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"center\" bgColor=\"#f5fafe\" class=\"ta_01\">商品名称：</td>\r\n");
      out.write("\t\t\t\t<td class=\"ta_01\" bgColor=\"#ffffff\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\tname=\"name\" class=\"bg\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\" bgColor=\"#f5fafe\" class=\"ta_01\">商品价格：</td>\r\n");
      out.write("\t\t\t\t<td class=\"ta_01\" bgColor=\"#ffffff\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\tname=\"price\" \r\n");
      out.write("\t\t\t\t\tclass=\"bg\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"center\" bgColor=\"#f5fafe\" class=\"ta_01\">商品数量：</td>\r\n");
      out.write("\t\t\t\t<td class=\"ta_01\" bgColor=\"#ffffff\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\tname=\"pnum\" \r\n");
      out.write("\t\t\t\t\tclass=\"bg\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\" bgColor=\"#f5fafe\" class=\"ta_01\">商品类别：</td>\r\n");
      out.write("\t\t\t\t<td class=\"ta_01\" bgColor=\"#ffffff\"><select name=\"category\"\r\n");
      out.write("\t\t\t\t\tid=\"category\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">--选择商品类加--</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"文学\">文学</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"生活\">生活</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"计算机\">计算机</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"外语\">外语</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"经营\">经营</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"励志\">励志</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"社科\">社科</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"学术\">学术</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"少儿\">少儿</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"艺术\">艺术</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"原版\">原版</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"科技\">科技</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"考试\">考试</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"生活百科\">生活百科</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"center\" bgColor=\"#f5fafe\" class=\"ta_01\">商品图片：</td>\r\n");
      out.write("\t\t\t\t<td class=\"ta_01\" bgColor=\"#ffffff\" colSpan=\"3\">\r\n");
      out.write("\t\t\t\t<input\r\n");
      out.write("\t\t\t\t\ttype=\"file\" name=\"upload\" size=\"30\" value=\"\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD class=\"ta_01\" align=\"center\" bgColor=\"#f5fafe\">商品描述：</TD>\r\n");
      out.write("\t\t\t\t<TD class=\"ta_01\" bgColor=\"#ffffff\" colSpan=\"3\">\r\n");
      out.write("\t\t\t\t<textarea\r\n");
      out.write("\t\t\t\t\t\tname=\"description\" cols=\"30\" rows=\"3\" \r\n");
      out.write("\t\t\t\t\t\tstyle=\"WIDTH: 96%\"></textarea>\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<td align=\"center\" colSpan=\"4\" class=\"sep1\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/images/shim.gif\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"ta_01\" style=\"WIDTH: 100%\" align=\"center\"\r\n");
      out.write("\t\t\t\t\tbgColor=\"#f5fafe\" colSpan=\"4\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" class=\"button_ok\" value=\"确定\">\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<FONT face=\"宋体\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</FONT>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"reset\" value=\"重置\" class=\"button_cancel\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<FONT face=\"宋体\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</FONT> <INPUT\r\n");
      out.write("\t\t\t\t\tclass=\"button_ok\" type=\"button\" onclick=\"history.go(-1)\" value=\"返回\" />\r\n");
      out.write("\t\t\t\t\t<span id=\"Label1\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
